"""add posts

Revision ID: dc3fdbf2bbc8
Revises: 5a5e12cb6220
Create Date: 2025-09-15 23:13:25.857027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc3fdbf2bbc8'
down_revision: Union[str, Sequence[str], None] = '5a5e12cb6220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('video_url', sa.String(length=1024), nullable=True),
    sa.Column('moderated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('published', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('time_published', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['public.users.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['public.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('ix_posts_time_created', 'posts', ['time_created'], unique=False, schema='public')
    op.create_table('comments_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['public.comments_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['public.posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('likes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['public.posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', name='uq_likes_user_post'),
    schema='public'
    )
    op.drop_constraint(op.f('agreements_clients_user_id_fkey'), 'agreements_clients', type_='foreignkey')
    op.create_foreign_key(None, 'agreements_clients', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('balance_operation_operation_type_id_fkey'), 'balance_operation', type_='foreignkey')
    op.drop_constraint(op.f('balance_operation_user_id_fkey'), 'balance_operation', type_='foreignkey')
    op.create_foreign_key(None, 'balance_operation', 'operation_type', ['operation_type_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'balance_operation', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('chat_attachment_message_id_fkey'), 'chat_attachment', type_='foreignkey')
    op.create_foreign_key(None, 'chat_attachment', 'chat_messages', ['message_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('chat_messages_sender_id_fkey'), 'chat_messages', type_='foreignkey')
    op.drop_constraint(op.f('chat_messages_chat_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'users', ['sender_id'], ['id'], referent_schema='public')
    op.create_foreign_key(None, 'chat_messages', 'chats', ['chat_id'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('chat_participant_chat_id_fkey'), 'chat_participant', type_='foreignkey')
    op.drop_constraint(op.f('chat_participant_user_id_fkey'), 'chat_participant', type_='foreignkey')
    op.create_foreign_key(None, 'chat_participant', 'chats', ['chat_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'chat_participant', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('chat_rating_chat_id_fkey'), 'chat_rating', type_='foreignkey')
    op.create_foreign_key(None, 'chat_rating', 'chats', ['chat_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('chats_user_id_fkey'), 'chats', type_='foreignkey')
    op.drop_constraint(op.f('chats_user_support_id_fkey'), 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'chats', 'users', ['user_support_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.drop_constraint(op.f('client_lawyer_assignment_client_id_fkey'), 'client_lawyer_assignment', type_='foreignkey')
    op.drop_constraint(op.f('client_lawyer_assignment_lawyer_id_fkey'), 'client_lawyer_assignment', type_='foreignkey')
    op.create_foreign_key(None, 'client_lawyer_assignment', 'users', ['lawyer_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'client_lawyer_assignment', 'users', ['client_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('court_stage_appointed_employee_id_fkey'), 'court_stage', type_='foreignkey')
    op.drop_constraint(op.f('court_stage_user_id_fkey'), 'court_stage', type_='foreignkey')
    op.create_foreign_key(None, 'court_stage', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'court_stage', 'users', ['appointed_employee_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('discount_association_agreement_id_fkey'), 'discount_association', type_='foreignkey')
    op.drop_constraint(op.f('discount_association_discount_id_fkey'), 'discount_association', type_='foreignkey')
    op.create_foreign_key(None, 'discount_association', 'discount', ['discount_id'], ['id'], referent_schema='public')
    op.create_foreign_key(None, 'discount_association', 'agreements_clients', ['agreement_id'], ['id'], referent_schema='public')
    op.drop_constraint(op.f('document_created_user_id_fkey'), 'document_created', type_='foreignkey')
    op.drop_constraint(op.f('document_created_document_id_fkey'), 'document_created', type_='foreignkey')
    op.create_foreign_key(None, 'document_created', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'document_created', 'documents', ['document_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('document_fields_document_id_fkey'), 'document_fields', type_='foreignkey')
    op.create_foreign_key(None, 'document_fields', 'documents', ['document_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('documents_user_user_id_fkey'), 'documents_user', type_='foreignkey')
    op.drop_constraint(op.f('documents_user_document_id_fkey'), 'documents_user', type_='foreignkey')
    op.create_foreign_key(None, 'documents_user', 'documents', ['document_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'documents_user', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('group_permission_association_group_id_fkey'), 'group_permission_association', type_='foreignkey')
    op.create_foreign_key(None, 'group_permission_association', 'groups', ['group_id'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('history_edit_schedule_schedule_id_fkey'), 'history_edit_schedule', type_='foreignkey')
    op.create_foreign_key(None, 'history_edit_schedule', 'payment_schedule', ['schedule_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('message_read_receipt_user_id_fkey'), 'message_read_receipt', type_='foreignkey')
    op.drop_constraint(op.f('message_read_receipt_message_id_fkey'), 'message_read_receipt', type_='foreignkey')
    op.create_foreign_key(None, 'message_read_receipt', 'chat_messages', ['message_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'message_read_receipt', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('payment_schedule_deducted_id_fkey'), 'payment_schedule', type_='foreignkey')
    op.drop_constraint(op.f('payment_schedule_agreement_id_fkey'), 'payment_schedule', type_='foreignkey')
    op.create_foreign_key(None, 'payment_schedule', 'agreements_clients', ['agreement_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'payment_schedule', 'discount', ['deducted_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('payments_requests_user_id_fkey'), 'payments_requests', type_='foreignkey')
    op.create_foreign_key(None, 'payments_requests', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('purchased_documents_document_id_fkey'), 'purchased_documents', type_='foreignkey')
    op.drop_constraint(op.f('purchased_documents_user_id_fkey'), 'purchased_documents', type_='foreignkey')
    op.create_foreign_key(None, 'purchased_documents', 'documents', ['document_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'purchased_documents', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('support_history_chat_reason_id_fkey'), 'support_history_chat', type_='foreignkey')
    op.drop_constraint(op.f('support_history_chat_old_support_id_fkey'), 'support_history_chat', type_='foreignkey')
    op.drop_constraint(op.f('support_history_chat_history_date_id_fkey'), 'support_history_chat', type_='foreignkey')
    op.drop_constraint(op.f('support_history_chat_chat_id_fkey'), 'support_history_chat', type_='foreignkey')
    op.create_foreign_key(None, 'support_history_chat', 'chats', ['chat_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'support_history_chat', 'support_history_date', ['history_date_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'support_history_chat', 'users', ['old_support_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'support_history_chat', 'reason_close_chat', ['reason_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('tokens_user_id_fkey'), 'tokens', type_='foreignkey')
    op.create_foreign_key(None, 'tokens', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('user_activity_user_id_fkey'), 'user_activity', type_='foreignkey')
    op.create_foreign_key(None, 'user_activity', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('user_balance_user_id_fkey'), 'user_balance', type_='foreignkey')
    op.create_foreign_key(None, 'user_balance', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('user_group_association_group_id_fkey'), 'user_group_association', type_='foreignkey')
    op.drop_constraint(op.f('user_group_association_user_id_fkey'), 'user_group_association', type_='foreignkey')
    op.create_foreign_key(None, 'user_group_association', 'groups', ['group_id'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_group_association', 'users', ['user_id'], ['id'], referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_group_association', type_='foreignkey')
    op.drop_constraint(None, 'user_group_association', type_='foreignkey')
    op.create_foreign_key(op.f('user_group_association_user_id_fkey'), 'user_group_association', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('user_group_association_group_id_fkey'), 'user_group_association', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'user_balance', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('user_balance_user_id_fkey'), 'user_balance', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'user_activity', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('user_activity_user_id_fkey'), 'user_activity', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'tokens', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tokens_user_id_fkey'), 'tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'support_history_chat', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'support_history_chat', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'support_history_chat', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'support_history_chat', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('support_history_chat_chat_id_fkey'), 'support_history_chat', 'chats', ['chat_id'], ['id'])
    op.create_foreign_key(op.f('support_history_chat_history_date_id_fkey'), 'support_history_chat', 'support_history_date', ['history_date_id'], ['id'])
    op.create_foreign_key(op.f('support_history_chat_old_support_id_fkey'), 'support_history_chat', 'users', ['old_support_id'], ['id'])
    op.create_foreign_key(op.f('support_history_chat_reason_id_fkey'), 'support_history_chat', 'reason_close_chat', ['reason_id'], ['id'])
    op.drop_constraint(None, 'purchased_documents', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'purchased_documents', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('purchased_documents_user_id_fkey'), 'purchased_documents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('purchased_documents_document_id_fkey'), 'purchased_documents', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'payments_requests', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('payments_requests_user_id_fkey'), 'payments_requests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'payment_schedule', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'payment_schedule', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('payment_schedule_agreement_id_fkey'), 'payment_schedule', 'agreements_clients', ['agreement_id'], ['id'])
    op.create_foreign_key(op.f('payment_schedule_deducted_id_fkey'), 'payment_schedule', 'discount', ['deducted_id'], ['id'])
    op.drop_constraint(None, 'message_read_receipt', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'message_read_receipt', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('message_read_receipt_message_id_fkey'), 'message_read_receipt', 'chat_messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('message_read_receipt_user_id_fkey'), 'message_read_receipt', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'history_edit_schedule', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('history_edit_schedule_schedule_id_fkey'), 'history_edit_schedule', 'payment_schedule', ['schedule_id'], ['id'])
    op.drop_constraint(None, 'group_permission_association', type_='foreignkey')
    op.create_foreign_key(op.f('group_permission_association_group_id_fkey'), 'group_permission_association', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'documents_user', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'documents_user', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('documents_user_document_id_fkey'), 'documents_user', 'documents', ['document_id'], ['id'])
    op.create_foreign_key(op.f('documents_user_user_id_fkey'), 'documents_user', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'document_fields', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('document_fields_document_id_fkey'), 'document_fields', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'document_created', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'document_created', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('document_created_document_id_fkey'), 'document_created', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('document_created_user_id_fkey'), 'document_created', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'discount_association', type_='foreignkey')
    op.drop_constraint(None, 'discount_association', type_='foreignkey')
    op.create_foreign_key(op.f('discount_association_discount_id_fkey'), 'discount_association', 'discount', ['discount_id'], ['id'])
    op.create_foreign_key(op.f('discount_association_agreement_id_fkey'), 'discount_association', 'agreements_clients', ['agreement_id'], ['id'])
    op.drop_constraint(None, 'court_stage', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'court_stage', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('court_stage_user_id_fkey'), 'court_stage', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('court_stage_appointed_employee_id_fkey'), 'court_stage', 'users', ['appointed_employee_id'], ['id'])
    op.drop_constraint(None, 'client_lawyer_assignment', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'client_lawyer_assignment', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('client_lawyer_assignment_lawyer_id_fkey'), 'client_lawyer_assignment', 'users', ['lawyer_id'], ['id'])
    op.create_foreign_key(op.f('client_lawyer_assignment_client_id_fkey'), 'client_lawyer_assignment', 'users', ['client_id'], ['id'])
    op.drop_constraint(None, 'chats', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'chats', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('chats_user_support_id_fkey'), 'chats', 'users', ['user_support_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('chats_user_id_fkey'), 'chats', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'chat_rating', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('chat_rating_chat_id_fkey'), 'chat_rating', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'chat_participant', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'chat_participant', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('chat_participant_user_id_fkey'), 'chat_participant', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('chat_participant_chat_id_fkey'), 'chat_participant', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_chat_id_fkey'), 'chat_messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('chat_messages_sender_id_fkey'), 'chat_messages', 'users', ['sender_id'], ['id'])
    op.drop_constraint(None, 'chat_attachment', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('chat_attachment_message_id_fkey'), 'chat_attachment', 'chat_messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'balance_operation', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'balance_operation', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('balance_operation_user_id_fkey'), 'balance_operation', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('balance_operation_operation_type_id_fkey'), 'balance_operation', 'operation_type', ['operation_type_id'], ['id'])
    op.drop_constraint(None, 'agreements_clients', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('agreements_clients_user_id_fkey'), 'agreements_clients', 'users', ['user_id'], ['id'])
    op.drop_table('likes', schema='public')
    op.drop_table('comments_posts', schema='public')
    op.drop_index('ix_posts_time_created', table_name='posts', schema='public')
    op.drop_table('posts', schema='public')
    # ### end Alembic commands ###
